# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /templates/Gemfile.erb

source "https://rubygems.org"

gem "fluentd", "1.7.1"
gem "fluent-plugin-secure-forward"
gem "fluent-plugin-record-reformer"
gem "fluent-plugin-kubernetes_metadata_filter"
gem "fluent-plugin-kinesis"
gem "fluent-plugin-systemd"
gem "fluent-plugin-rewrite-tag-filter"
gem "fluent-plugin-multi-format-parser"
gem "fluent-plugin-record-modifier"
gem "fluent-plugin-s3"
